框架流程代码解读
lilith-avatar/avatar-ava pull request #60
Opened 2021-07-30 15:50 UTC by dhq1233223

针对框架流程的代码进行解读，详情可阅读Smap文件夹下的说明.txt

2021-07-30 17:01 UTC, lilith-avatar-yenyuan commented
你好，你似乎多了一些你自己的文件，建议再看看

2021-07-30 17:46 UTC, endaye requested changes
同学你好，你的批注非常棒！

现在我们遇到的问题是：批注里使用的AvaKit框架是`v2.5`版本的现在主干分支`main`上的版本是`v3.0`，项目结构有了一些比较大的改动，所以这里会有一些冲突。希望你可以pull一下最新的`main`分支，本地升级到最新版的AvaKit，将批注相关的代码本地合入后发`pull-request`，这样我们在review无误后会尽快合入项目主干。

最后，感谢你对AvaKit和达芬奇计划的支持！加油🦾

2021-07-31 02:13 UTC, dhq1233223 commented
载入框架3.0.0，并对ServerModule、ServerHeartbeatModule 、ClientModule、ClientHeartbeatModule四个模块进行注释修正解读。其他模块由于版本迭代消失或者修改了原解读无法继续使用，所有没有进行注释解读

2021-08-01 12:39 UTC, endaye approved these changes
非常赞！太帅了！故Approve。

但是有几个小小的问题：
* 注意批注的缩进，现阶段我们统一用vscode插件[`LuaCoderAssist`](https://marketplace.visualstudio.com/items?itemName=liwangqian.luacoderassist)进行代码格式统一；
* `function`内部的批注统一已`-- XXXX`来进行批注；
* 针对`ModuleScript`或者`Script`用`--- XXXX`来进行批注；
* 如果只是改了lua代码，则`.smap`文件可以不用上传，合入主干后会有人统一合入；
* 以上问题我们会在下周统一对此pr的内容进行修改。

最后，再次感谢 @dhq1233223 同学对达芬奇计划的大力支持！
辛苦了 bro 💪

2021-08-01 12:41 UTC, merged